#!/bin/bash

NGINX_DIR="nginx-1.22.0"
SGX_SDK="/opt/intel/sgxsdk"
DIR="../ngx_http_custom_load_balancer"
OPENSSL_LIBRARY_PATH="/opt/intel/sgxssl/lib64"
FLAG="-g -I $SGX_SDK/lib64 -I $SGX_SDK/include -I $DIR/Include -I $DIR/App -I $DIR/Enclave -lsgx_urts -lpthread -lcrypto -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable" 
FLAG2="-g -lsgx_urts -lpthread -lcrypto -L$OPENSSL_LIBRARY_PATH -lsgx_usgxssl"
PREFIX="$PWD/nginx-1.22.0/build"
cd $NGINX_DIR
./configure --prefix=$PREFIX --add-module=$DIR --with-cc-opt="$FLAG" --with-ld-opt="$FLAG2"
